version: '3'

services:
  topup-service:
    # image: docker.simplicy.io/topup-service:latest
    build: .
    ports:
      - "7700:7700"
    environment:
      - RPC_URI=http://172.17.0.1:7545
      - NODE_ENV=production
      - STRIPE_PUBLIC_KEY=${STRIPE_PUBLIC_KEY}               
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}               
      - WALLET_ADDRESS=${WALLET_ADDRESS}               
      - BLOCKCHAIN_CLIENT_URL=${BLOCKCHAIN_CLIENT_URL}               
                
# Needs blockchain client running on provided BLOCKCHAIN_CLIENT_URL;
