name: Build Blockchain Client

on:
  push:
    branches: [ main ]
    paths:
      - "packages/blockchain-client"

jobs:
  build_blockchain_client:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: docker.simplicy.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: docker.simplicy.io/blockchain-client:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
