name: Build Blockchain Client

on:
  push:
    branches: [ main ]
    tags:
      - "v*.*.*"
    paths:
      - "packages/blockchain-client/**"

jobs:
  build_blockchain_client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          # list of Docker images to use as base name for tags
          images: |
            docker.simplicy.io/blockchain-client
          # add git short SHA as Docker tag
          tag-semver: |
            {{raw}}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: docker.simplicy.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: packages/blockchain-client
          push: true
          repository: docker.simplicy.io/blockchain-client
          tags: ${{ steps.docker_meta.outputs.tags }}
