name: Test Simplicy Mobile

on:
  pull_request:
    branches: [ main ]
    paths:
      - "packages/simplicy-mobile/**"

defaults:
  run:
    working-directory: packages/simplicy-mobile

jobs:
  test_blockchain_client:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - uses: nanasess/setup-chromedriver@master
    - run: |
        export DISPLAY=:99
        export NODE_ENV=test
        chromedriver --url-base=/wd/hub &
        npm ci
        npm run format:check
        npm run lint
        npm run test
        npm run e2e
